# Restaurant Sales Data Analysis

In this dataset we have the sales data of a restaurant data from different countries (cities).

We are going to analyze and visualize the data, the data is available in excel formate.

In [1]:
import pandas as pd

In [4]:
sales_data = pd.read_excel("1_Sales_Data.xlsx")

sales_data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,NaN,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,NaN,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,NaN,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
...,...,...,...,...,...,...,...,...,...,...
250,NaN,10709,2022-12-28 00:00:00,Sides & Other,4.99,200.400802,Drive-thru,Gift Card,Walter Muller,Berlin
251,NaN,10710,2022-12-29 00:00:00,Burgers,12.99,754.426482,Drive-thru,Gift Card,Walter Muller,Berlin
252,NaN,10711,2022-12-29 00:00:00,Chicken Sandwiches,9.95,281.407035,Drive-thru,Gift Card,Walter Muller,Berlin
253,NaN,10712,2022-12-29 00:00:00,Fries,3.49,630.372493,Drive-thru,Gift Card,Walter Muller,Berlin
254,NaN,10713,2022-12-29 00:00:00,Beverages,2.95,677.966102,Drive-thru,Gift Card,Walter Muller,Berlin

In [5]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  255 non-null    object
 2   Unnamed: 2  255 non-null    object
 3   Unnamed: 3  255 non-null    object
 4   Unnamed: 4  255 non-null    object
 5   Unnamed: 5  255 non-null    object
 6   Unnamed: 6  255 non-null    object
 7   Unnamed: 7  255 non-null    object
 8   Unnamed: 8  255 non-null    object
 9   Unnamed: 9  255 non-null    object
dtypes: float64(1), object(9)
memory usage: 20.1+ KB

In [ ]:
# Remove unwanted column.

sales_data.drop(columns= "Unnamed: 0", inplace= True)

In [8]:
sales_data.head()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [9]:
# Change the name of columns.
# As we can see that the name of the columns are written "Unnamed"
# because in our excel sheet we have the first row empty.

sales_data.loc[0]

Unnamed: 1          Order ID
Unnamed: 2              Date
Unnamed: 3           Product
Unnamed: 4             Price
Unnamed: 5          Quantity
Unnamed: 6     Purchase Type
Unnamed: 7    Payment Method
Unnamed: 8           Manager
Unnamed: 9              City
Name: 0, dtype: object

In [10]:
sales_data.columns

Index(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [11]:
# To change the column name we will use this syntax.

sales_data.columns = sales_data.loc[0]

In [12]:
sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [ ]:
# Now we have to remove the row at index 0. 

sales_data.drop(0, inplace=True)

sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [24]:
# Remove empty space from the "Manager" column.

sales_data.Manager

# We can see there are spaces between the names.

1        Tom      Jackson
2             Pablo Perez
3           Joao    Silva
4           Walter Muller
5           Walter Muller
              ...
250         Walter Muller
251         Walter Muller
252         Walter Muller
253         Walter Muller
254         Walter Muller
Name: Manager, Length: 254, dtype: object

In [25]:
sales_data.Manager.unique()

array(['Tom      Jackson', '       Pablo Perez', 'Joao    Silva',
       'Walter Muller', 'Remy    Monet', 'Remy Monet',
       '       Remy Monet', 'Remy     Monet', 'Pablo Perez',
       'Pablo   Perez', 'Pablo  Perez', 'Pablo    Perez', 'Joao Silva',
       'Tom Jackson'], dtype=object)

In [27]:
# Syntax to remove the spaces and make changes to the column.

sales_data["Manager"] = sales_data["Manager"].str.strip().str.replace(r"\s+", " ", regex= True)

In [30]:
sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [1]:
import pandas as pd

sales_data = pd.read_excel("1_Sales_Data.xlsx")
sales_data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,NaN,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,NaN,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,NaN,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [2]:
# Remove Unwanted column.

sales_data.drop(columns= "Unnamed: 0", inplace=True)

In [4]:
# To change the column name we will use this syntax.

sales_data.columns = sales_data.loc[0]

sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [5]:
# Now we have to remove the row at index 0. 

sales_data.drop(0, inplace=True)

sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [6]:
# Rremove empty space.

sales_data["Manager"] = sales_data["Manager"].str.strip().str.replace(r"\s+", " ", regex= True)

sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [8]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 1 to 254
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    object
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    object
 4   Quantity        254 non-null    object
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: object(9)
memory usage: 18.0+ KB

In [ ]:
# Convert the data type of column "Order ID" and "Quantity" into numeric formate.

# To change the datatype of column into numeric which has decimal value, first we have to convert to float value. 
sales_data["Quantity"] = sales_data["Quantity"].astype(float)

sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 1 to 254
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    object
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    object
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: float64(1), object(8)
memory usage: 18.0+ KB

In [17]:
sales_data["Quantity"] = sales_data["Quantity"].round()

sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 1 to 254
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    object
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    object
 4   Quantity        254 non-null    int64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: int64(1), object(8)
memory usage: 18.0+ KB

In [18]:
sales_data["Quantity"] = sales_data["Quantity"].astype(int)

sales_data["Quantity"]

# if we directly convert the type, we will show the value 745 with out rounding of.

1      573
2      746
3      200
4      570
5      201
      ...
250    200
251    754
252    281
253    630
254    678
Name: Quantity, Length: 254, dtype: int64

In [19]:
# Convert datatype of Order ID column
sales_data["Order ID"] = sales_data["Order ID"].astype(int)

sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 1 to 254
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    object
 4   Quantity        254 non-null    int64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: int64(2), object(7)
memory usage: 18.0+ KB

In [3]:
import pandas as pd

sales_data = pd.read_excel("1_Sales_Data.xlsx")

sales_data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,NaN,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,NaN,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,NaN,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [4]:
sales_data.drop(columns= "Unnamed: 0", inplace=True)

sales_data.columns = sales_data.loc[0]

sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [6]:

sales_data["Manager"] = sales_data["Manager"].str.strip().str.replace(r"\s+", " ", regex= True)


sales_data.drop(0, inplace=True)


sales_data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [ ]:
sales_data["Quantity"] = sales_data["Quantity"].astype(float)

sales_data["Quantity"] = sales_data["Quantity"].round()

sales_data["Quantity"] = sales_data["Quantity"].astype(int)

sales_data["Order ID"] = sales_data["Order ID"].astype(int)

# Convert the datatype of "Date" column from object to datetime.
sales_data["Date"] = pd.to_datetime(sales_data["Date"])

sales_data.info()

# Now the data has been clean, Now we will do analysis

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 1 to 254
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    datetime64[ns]
 2   Product         254 non-null    object
 3   Price           254 non-null    object
 4   Quantity        254 non-null    int64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 18.0+ KB

## Analyze The Data.

### Q) 1. What is the most prefered payment method.

In [9]:
sales_data["Payment Method"].unique()

array([' Gift Card', ' Credit Card', ' Cash'], dtype=object)

In [10]:
# Show the count for each payment method

sales_data["Payment Method"].value_counts()

Payment Method
Credit Card    120
Cash            76
Gift Card       58
Name: count, dtype: int64

In [11]:
# Show it in percentage.

sales_data["Payment Method"].value_counts(normalize=True)*100

Payment Method
Credit Card    47.244094
Cash           29.921260
Gift Card      22.834646
Name: proportion, dtype: float64